[package]
name = "hidapi-sys"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.36"
cmake = "0.1.54"
pkg-config = "0.3.32"
